/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package qmath;

public class Library {
    
    /*
     * Checks if the given number is an even number
     */
    public boolean isEven(int n)
    {
        return n % 2 == 0;
    }
    
    /*
     * add two integers - overloading
     */
    public int add(int a, int b) {
        return a + b;
    }

    /*
     * add two float numbers - overloding
     */
    public float add(float a, float b) {
        return a + b;
    }
}
