/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package qmath;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void isEven() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.isEven(2));
    }
}
